-- apply changes
create table access (
  id                            bigint generated by default as identity not null,
  module_id                     bigint,
  created_by_id                 bigint,
  last_updated_by_id            bigint,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  external_id                   varchar(16),
  name                          varchar(150) default '',
  alias                         varchar(150) default '',
  constraint uq_access_external_id unique (external_id),
  constraint uq_access_name unique (name),
  constraint pk_access primary key (id)
);

create table access_roles (
  id                            bigint generated by default as identity not null,
  access_id                     bigint,
  role_id                       bigint,
  created_by_id                 bigint,
  last_updated_by_id            bigint,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  permission                    varchar(7),
  constraint ck_access_roles_permission check ( permission in ('ALLOWED','DENIED')),
  constraint pk_access_roles primary key (id)
);

create table admins (
  id                            bigint generated by default as identity not null,
  cms_user_id                   bigint,
  birthday                      date,
  complete                      boolean default false not null,
  superadmin                    boolean default false not null,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  external_id                   varchar(16),
  full_name                     varchar(200) default '',
  thumbnail_profile_image       varchar(255),
  original_profile_image        varchar(255),
  gender                        varchar(9),
  constraint ck_admins_gender check ( gender in ('MALE','FEMALE','UNDEFINED')),
  constraint uq_admins_cms_user_id unique (cms_user_id),
  constraint uq_admins_external_id unique (external_id),
  constraint pk_admins primary key (id)
);

create table admin_notifications (
  id                            bigint generated by default as identity not null,
  admin_id                      bigint,
  actor_id                      bigint,
  created_at                    timestamp not null,
  external_id                   varchar(16),
  message                       text,
  status                        varchar(4),
  constraint ck_admin_notifications_status check ( status in ('NEW','READ')),
  constraint uq_admin_notifications_external_id unique (external_id),
  constraint pk_admin_notifications primary key (id)
);

create table api_keys (
  id                            bigint generated by default as identity not null,
  cms_user_id                   bigint,
  expired_time                  timestamp,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  external_id                   varchar(16),
  access_token                  varchar(510),
  ip_address                    varchar(50),
  location                      varchar(50),
  browser                       varchar(255),
  operating_system              varchar(255),
  reg_token                     varchar(510),
  imei                          varchar(16),
  constraint uq_api_keys_external_id unique (external_id),
  constraint uq_api_keys_cms_user_id unique (cms_user_id),
  constraint pk_api_keys primary key (id)
);

create table app_settings (
  id                            bigint generated by default as identity not null,
  setting_group_id              bigint,
  created_by_id                 bigint,
  last_updated_by_id            bigint,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  external_id                   varchar(16),
  setting_key                   varchar(150),
  setting_value                 varchar(50),
  setting_type                  varchar(8) default 'BOOLEAN',
  setting_options               varchar[],
  constraint ck_app_settings_setting_type check ( setting_type in ('BOOLEAN','TEXT','NUMERIC','RADIO','MULTIPLE')),
  constraint uq_app_settings_external_id unique (external_id),
  constraint uq_app_settings_setting_key unique (setting_key),
  constraint pk_app_settings primary key (id)
);

create table banners (
  id                            bigint generated by default as identity not null,
  sequence                      integer default 0 not null,
  status                        boolean default false not null,
  created_at                    timestamp not null,
  updated_at                    timestamp not null,
  external_id                   varchar(16),
  title                         varchar(255),
  description                   varchar(255),
  image                         varchar(255),
  link_url                      varchar(255),
  type                          varchar(18),
  constraint ck_banners_type check ( type in ('LEFT_BANNER','RIGHT_BANNER','HOMEPAGE_SLIDESHOW')),
  constraint uq_banners_external_id unique (external_id),
  constraint pk_banners primary key (id)
);

create table users (
  id                            bigint generated by default as identity not null,
  role_id                       bigint,
  email_verified                boolean default false not null,
  phone_verified                boolean default false not null,
  token_expired_on              timestamp,
  token_phone_expired_on        timestamp,
  forgot_code_expired_on        timestamp,
  last_send_token               timestamp,
  last_send_token_phone         timestamp,
  last_login                    timestamp,
  last_seen                     timestamp,
  locked                        boolean default false not null,
  auto_unlocked_at              timestamp,
  login_attempt                 integer default 0 not null,
  created_by_id                 bigint,
  last_updated_by_id            bigint,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  external_id                   varchar(16),
  email                         varchar(100),
  username                      varchar(50),
  password                      varchar(500),
  new_email                     varchar(100),
  phone                         varchar(50),
  token                         varchar(20),
  token_phone                   varchar(10),
  forgot_code                   varchar(20),
  online_status                 varchar(6) default 'AWAY' not null,
  status                        varchar(9) not null,
  constraint ck_users_online_status check ( online_status in ('ACTIVE','AWAY')),
  constraint ck_users_status check ( status in ('PENDING','ACTIVE','SUSPENDED')),
  constraint uq_users_external_id unique (external_id),
  constraint uq_users_email unique (email),
  constraint uq_users_username unique (username),
  constraint uq_users_new_email unique (new_email),
  constraint uq_users_phone unique (phone),
  constraint pk_users primary key (id)
);

create table user_settings (
  id                            bigint generated by default as identity not null,
  cms_user_id                   bigint,
  timezone_offset               bigint not null,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  odds_format                   varchar(5),
  constraint uq_user_settings_cms_user_id unique (cms_user_id),
  constraint pk_user_settings primary key (id)
);

create table countries (
  id                            bigint generated by default as identity not null,
  created_by_id                 bigint,
  last_updated_by_id            bigint,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  external_id                   varchar(16),
  alpha2_code                   varchar(2),
  alpha3_code                   varchar(3),
  name                          varchar(100),
  calling_code                  varchar(10),
  currency                      varchar(255),
  currency_symbol               varchar(255),
  geoname_id                    varchar(255),
  constraint uq_countries_external_id unique (external_id),
  constraint uq_countries_name unique (name),
  constraint pk_countries primary key (id)
);

create table internal_settings (
  id                            bigint generated by default as identity not null,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  setting_key                   varchar(150),
  setting_value                 varchar(50),
  constraint uq_internal_settings_setting_key unique (setting_key),
  constraint pk_internal_settings primary key (id)
);

create table modules (
  id                            bigint generated by default as identity not null,
  created_by_id                 bigint,
  last_updated_by_id            bigint,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  external_id                   varchar(16),
  code                          varchar(5),
  name                          varchar(100),
  summary                       varchar(255),
  constraint uq_modules_external_id unique (external_id),
  constraint uq_modules_code unique (code),
  constraint uq_modules_name unique (name),
  constraint pk_modules primary key (id)
);

create table module_roles (
  id                            bigint generated by default as identity not null,
  module_id                     bigint,
  role_id                       bigint,
  created_by_id                 bigint,
  last_updated_by_id            bigint,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  permission                    varchar(7),
  constraint ck_module_roles_permission check ( permission in ('ALLOWED','DENIED')),
  constraint pk_module_roles primary key (id)
);

create table roles (
  id                            bigint generated by default as identity not null,
  created_by_id                 bigint,
  last_updated_by_id            bigint,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  external_id                   varchar(16),
  name                          varchar(50),
  alias                         varchar(50),
  description                   varchar(255),
  constraint uq_roles_external_id unique (external_id),
  constraint pk_roles primary key (id)
);

create table setting_groups (
  id                            bigint generated by default as identity not null,
  created_by_id                 bigint,
  last_updated_by_id            bigint,
  created_at                    timestamp not null,
  last_updated_at               timestamp not null,
  external_id                   varchar(16),
  name                          varchar(150),
  constraint uq_setting_groups_external_id unique (external_id),
  constraint uq_setting_groups_name unique (name),
  constraint pk_setting_groups primary key (id)
);

create table temp_files (
  id                            bigint generated by default as identity not null,
  expired_at                    timestamp,
  created_at                    timestamp default '2022-12-12 00:00:00' not null,
  object_key                    varchar(255),
  media_link                    varchar(255),
  type                          varchar(11),
  constraint ck_temp_files_type check ( type in ('ATTACHMENTS')),
  constraint pk_temp_files primary key (id)
);

-- foreign keys and indices
create index ix_access_module_id on access (module_id);
alter table access add constraint fk_access_module_id foreign key (module_id) references modules (id) on delete restrict on update restrict;

create index ix_access_created_by_id on access (created_by_id);
alter table access add constraint fk_access_created_by_id foreign key (created_by_id) references admins (id) on delete restrict on update restrict;

create index ix_access_last_updated_by_id on access (last_updated_by_id);
alter table access add constraint fk_access_last_updated_by_id foreign key (last_updated_by_id) references admins (id) on delete restrict on update restrict;

create index ix_access_roles_access_id on access_roles (access_id);
alter table access_roles add constraint fk_access_roles_access_id foreign key (access_id) references access (id) on delete restrict on update restrict;

create index ix_access_roles_role_id on access_roles (role_id);
alter table access_roles add constraint fk_access_roles_role_id foreign key (role_id) references roles (id) on delete restrict on update restrict;

create index ix_access_roles_created_by_id on access_roles (created_by_id);
alter table access_roles add constraint fk_access_roles_created_by_id foreign key (created_by_id) references admins (id) on delete restrict on update restrict;

create index ix_access_roles_last_updated_by_id on access_roles (last_updated_by_id);
alter table access_roles add constraint fk_access_roles_last_updated_by_id foreign key (last_updated_by_id) references admins (id) on delete restrict on update restrict;

alter table admins add constraint fk_admins_cms_user_id foreign key (cms_user_id) references users (id) on delete restrict on update restrict;

create index ix_admin_notifications_admin_id on admin_notifications (admin_id);
alter table admin_notifications add constraint fk_admin_notifications_admin_id foreign key (admin_id) references admins (id) on delete restrict on update restrict;

create index ix_admin_notifications_actor_id on admin_notifications (actor_id);
alter table admin_notifications add constraint fk_admin_notifications_actor_id foreign key (actor_id) references users (id) on delete restrict on update restrict;

alter table api_keys add constraint fk_api_keys_cms_user_id foreign key (cms_user_id) references users (id) on delete restrict on update restrict;

create index ix_app_settings_setting_group_id on app_settings (setting_group_id);
alter table app_settings add constraint fk_app_settings_setting_group_id foreign key (setting_group_id) references setting_groups (id) on delete restrict on update restrict;

create index ix_app_settings_created_by_id on app_settings (created_by_id);
alter table app_settings add constraint fk_app_settings_created_by_id foreign key (created_by_id) references admins (id) on delete restrict on update restrict;

create index ix_app_settings_last_updated_by_id on app_settings (last_updated_by_id);
alter table app_settings add constraint fk_app_settings_last_updated_by_id foreign key (last_updated_by_id) references admins (id) on delete restrict on update restrict;

create index ix_users_role_id on users (role_id);
alter table users add constraint fk_users_role_id foreign key (role_id) references roles (id) on delete restrict on update restrict;

create index ix_users_created_by_id on users (created_by_id);
alter table users add constraint fk_users_created_by_id foreign key (created_by_id) references users (id) on delete restrict on update restrict;

create index ix_users_last_updated_by_id on users (last_updated_by_id);
alter table users add constraint fk_users_last_updated_by_id foreign key (last_updated_by_id) references users (id) on delete restrict on update restrict;

alter table user_settings add constraint fk_user_settings_cms_user_id foreign key (cms_user_id) references users (id) on delete restrict on update restrict;

create index ix_countries_created_by_id on countries (created_by_id);
alter table countries add constraint fk_countries_created_by_id foreign key (created_by_id) references admins (id) on delete restrict on update restrict;

create index ix_countries_last_updated_by_id on countries (last_updated_by_id);
alter table countries add constraint fk_countries_last_updated_by_id foreign key (last_updated_by_id) references admins (id) on delete restrict on update restrict;

create index ix_modules_created_by_id on modules (created_by_id);
alter table modules add constraint fk_modules_created_by_id foreign key (created_by_id) references admins (id) on delete restrict on update restrict;

create index ix_modules_last_updated_by_id on modules (last_updated_by_id);
alter table modules add constraint fk_modules_last_updated_by_id foreign key (last_updated_by_id) references admins (id) on delete restrict on update restrict;

create index ix_module_roles_module_id on module_roles (module_id);
alter table module_roles add constraint fk_module_roles_module_id foreign key (module_id) references modules (id) on delete restrict on update restrict;

create index ix_module_roles_role_id on module_roles (role_id);
alter table module_roles add constraint fk_module_roles_role_id foreign key (role_id) references roles (id) on delete restrict on update restrict;

create index ix_module_roles_created_by_id on module_roles (created_by_id);
alter table module_roles add constraint fk_module_roles_created_by_id foreign key (created_by_id) references admins (id) on delete restrict on update restrict;

create index ix_module_roles_last_updated_by_id on module_roles (last_updated_by_id);
alter table module_roles add constraint fk_module_roles_last_updated_by_id foreign key (last_updated_by_id) references admins (id) on delete restrict on update restrict;

create index ix_roles_created_by_id on roles (created_by_id);
alter table roles add constraint fk_roles_created_by_id foreign key (created_by_id) references admins (id) on delete restrict on update restrict;

create index ix_roles_last_updated_by_id on roles (last_updated_by_id);
alter table roles add constraint fk_roles_last_updated_by_id foreign key (last_updated_by_id) references admins (id) on delete restrict on update restrict;

create index ix_setting_groups_created_by_id on setting_groups (created_by_id);
alter table setting_groups add constraint fk_setting_groups_created_by_id foreign key (created_by_id) references admins (id) on delete restrict on update restrict;

create index ix_setting_groups_last_updated_by_id on setting_groups (last_updated_by_id);
alter table setting_groups add constraint fk_setting_groups_last_updated_by_id foreign key (last_updated_by_id) references admins (id) on delete restrict on update restrict;

