-- apply changes
create table activity_logs (
  id                            bigint generated by default as identity not null,
  actor_id                      bigint,
  created_at                    timestamp not null,
  external_id                   varchar(16),
  description                   text,
  constraint uq_activity_logs_external_id unique (external_id),
  constraint pk_activity_logs primary key (id)
);

-- foreign keys and indices
create index ix_activity_logs_actor_id on activity_logs (actor_id);
alter table activity_logs add constraint fk_activity_logs_actor_id foreign key (actor_id) references admins (id) on delete restrict on update restrict;

